version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cerberus-postgres
    environment:
      POSTGRES_DB: cerberus
      POSTGRES_USER: cerberus_user
      POSTGRES_PASSWORD: cerberus_password
    ports:
      - "5433:5432"
    volumes:
      - cerberus-postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cerberus_user -d cerberus"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - cerberus-network

  api:
    build:
      context: .
      dockerfile: Cerberus/Dockerfile
    container_name: cerberus-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CerberusDatabase=Host=postgres;Port=5432;Database=cerberus;Username=cerberus_user;Password=cerberus_password
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - cerberus-network

networks:
  cerberus-network:
    driver: bridge

volumes:
  cerberus-postgres-data:
    name: cerberus-postgres-data
